# Generated by Django 5.1.4 on 2025-01-05 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_hero_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='video_url',
        ),
        migrations.AddField(
            model_name='hero',
            name='main_hero',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='hero_media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_media/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carousel_img/'),
        ),
    ]
