# Generated by Django 5.1.4 on 2025-01-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_hero_video_url_hero_main_hero_hero_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='hero',
            name='main_hero',
            field=models.BooleanField(default=False),
        ),
    ]
