# Generated by Django 5.1.4 on 2025-01-05 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_published_date_alter_hero_main_hero'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='HeroList',
        ),
    ]
