# Generated by Django 5.1.4 on 2025-01-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_productlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductList',
            new_name='Product',
        ),
    ]
